import {Providers} from "./providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../components/ui/Navbar';
import {NextUIProvider} from "@nextui-org/react";
import Nav from "@/components/ui/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Defcon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>   <Providers>
        <div className="overflow-hidden">
      <Nav/>
          {children}
          </div>
        </Providers></body>
    </html>
  );
}
